export const _nav = [
  {
    title: 'Página Principal',
    path: '/dashboard',
    icon: 'nav-icon fas fa-tachometer-alt',
    routerLinkActive: 'active',
  },
  {
    title: 'CRM',
    path: '#',
    icon: 'nav-icon fas fa-sitemap',
    iconRight: 'right fas fa-angle-left',
    routerLinkActive: 'menu-open',
    permissionActiveRouterLink: 'list-crm',
    children: [
      {
        title: 'Clientes',
        path: '#',
        icon: 'icon-user nav-icon',
        iconRight: 'right fas fa-angle-left',
        routerLinkActive: 'menu-open',
        permissionActiveRouterLink: 'list-crm',
        children: [
          {
            title: 'Consultar Clientes',
            path: '/crm/clientes/consultar-clientes',
            icon: 'icon-user nav-icon',
            iconRight: 'right fas fa-angle-left',
            routerLinkActive: 'active',
            permissionActiveRouterLink: 'list-clientes',
          },
          {
            title: 'Conta Corrente',
            path: '/crm/clientes/cc',
            icon: 'far fa-cc nav-icon',
            routerLinkActive: 'active',
            permissionActiveRouterLink: 'list-clientes',
          },
          {
            title: 'Cartões',
            path: '/crm/clientes/cartoes',
            icon: 'far fa-credit-card nav-icon',
            routerLinkActive: 'active',
            permissionActiveRouterLink: 'list-cartao',
          },
        ],
      }, 
      {
        title: 'Orçamentos',
        path: '#',
        icon: 'far fa-circle nav-icon',
        iconRight: 'right fas fa-angle-left',
        routerLinkActive: 'menu-open',
        children: [
          {
            title: 'Registar',
            path: '/crm/orcamentos/registar-orcamento',
            icon: 'fa fa-plus nav-icon',
            routerLinkActive: 'active',
            permissionActiveRouterLink: 'create-orcamentos',
          },
          {
            title: 'Listar',
            path: '/crm/orcamentos/registar-orcamento',
            icon: 'far fa-cc nav-icon',
            routerLinkActive: 'active',
            permissionActiveRouterLink: 'list-orcamentos',
          },
        ],
      },
      {
        title: 'Acordos',
        path: '#',
        icon: 'far fa-folder nav-icon',
        iconRight: 'right fas fa-angle-left',
        routerLinkActive: 'menu-open',
        permissionActiveRouterLink: 'list-acordos',
        children: [
          {
            title: 'Novo Acordo',
            path: '/crm/acordos/registar',
            icon: 'far fa-folder nav-icon',
            routerLinkActive: 'active',
            permissionActiveRouterLink: 'create-acordos',
          },
          {
            title: 'Consultar acordos',
            path: '/crm/acordos/listar',
            icon: 'fa fa-search nav-icon',
            routerLinkActive: 'active',
            permissionActiveRouterLink: 'list-acordos',
          },
        ],
      },
    ],
  },
  {
    title: 'Logística',
    path: '#',
    icon: 'nav-icon fa fa-cogs',
    iconRight: 'right fas fa-angle-left',
    routerLinkActive: 'menu-open',
    permissionActiveRouterLink: 'list-logistica',
    children: [
      {
        title: 'Novo Acordo',
        path: '/crm/acordos/registar',
        icon: 'far fa-folder nav-icon',
        routerLinkActive: 'active',
        permissionActiveRouterLink: 'create-acordos',
      },
    ],
  },
];
